-- DATE 25 - 02 - 2023
-- LECTURE NO 11
-- TOPIC: ER DIAGRAM


-- ER DIAGRAM INTRODUCTION
-- ER DIAGRAM IS A VISUAL REPRESENTATION OF A DATABASE SCHEMA
-- IT SHOWS THE RELATIONSHIPS BETWEEN THE TABLES
-- IT IS USED TO MODEL THE STRUCTURE OF A DATABASE
-- ER DIAGRAM IS A VISUAL REPRESENTATION OF A DATABASE SCHEMA

-- ER DIAGRAM CONCEPTS
-- 1. ENTITY
-- 2. ATTRIBUTE
-- 3. RELATIONSHIP

-- 1. ENTITY
-- ENTITY IS A LOGICAL UNIT THAT REPRESENTS A TABLE IN A DATABASE
-- eg. STUDENT , COURSE

-- 2. ATTRIBUTE
-- ATTRIBUTE IS A PROPERTY OF AN ENTITY THAT REPRESENTS A COLUMN IN A TABLE
-- eg. NAME , ROLL NO , MARKS , DEPARTMENT

-- 3. RELATIONSHIP
-- RELATIONSHIP IS A CONNECTION BETWEEN TWO ENTITIES
-- IT CAN BE ONE TO ONE, ONE TO MANY, MANY TO ONE, MANY TO MANY
-- eg. STUDENT TO COURSE