-- DBMS -> DISTRIBUTED DATABASE MANAGEMENT SYSTEM
-- RDBMS -> RELATIONAL DATABASE MANAGEMENT SYSTEM
-- SQL -> STRUCTURED QUERY LANGUAGE
-- MYSQL
-- MS SQL
-- ORACLE

-- BASIC COMMANDS


-- 1. CREATE DATABASE
-- KEYWORD --> DATABASE
CREATE DATABASE CSE; -- FIRST QUERY


-- 2. DROP DATABASE
-- KEYWORD --> DATABASE
-- DROP DATABASE CSE;

-- 3. SHOW DATABASES
SHOW DATABASES;

-- 4. USE DATABASE NAME CSE
-- SYNTAX
-- USE DATABASE_NAME
USE CSE;


-- 5 . CRATE TABLE IN DATABASE
-- SYNTAX
-- CRATE TABLE TABLE_NAME
CREATE TABLE CSE_STUDENTS(
    ROLL_NO INT ,
    FIRST_NAME VARCHAR(30) ,
    LAST_NAME VARCHAR(30) ,
    EMAIL VARCHAR(30),
    AGE INT
);

-- 6. SHOW TABLE
SHOW TABLES;

-- 7. DESCRIBE TABLE --> SHOW TABLE STRUCTURE
DESCRIBE CSE_STUDENTS;

-- 8 . INSERT INTO TABLE
-- SYNTAX
-- A --> SINGLE ROW
-- INSERT INTO TABLE_NAME VALUES(value1 , value2 , value3 , value4 , value5);
INSERT INTO CSE_STUDENTS VALUES(
    51,'GOVIND','JANGID','govindjangidt@gmail.com',19
)

-- B --> MULTIPLE ROW
INSERT INTO CSE_STUDENTS VALUES
(
    47,'DILIP','KUMAWAT','dilipkumawat@gmail.com',20
)

INSERT INTO CSE_STUDENTS VALUES(
    50,"GOURAV","NAGORI",'gouravnagori@gmail.com',21
)

INSERT INTO CSE_STUDENTS VALUES(
    17,'AMAN','RAJPUT','AMAN@gmail.com',22
)

INSERT INTO CSE_STUDENTS VALUES(
    44,'DEVANSH','MAINI','DEVANSH@gmail.com',22
)


INSERT INTO CSE_STUDENTS VALUES(
    30,'ARYAN','KUMAR SINGH','ARYAN22@gmail.com',22
)

INSERT INTO CSE_STUDENTS VALUES(
    02,'ARYAN','SHARMA','ARYAN2@gmail.com',22
)

INSERT INTO CSE_STUDENTS VALUES(
    0023,'AKSHAT','VERMA','AKSHAT@gmail.com',22
)

INSERT INTO CSE_STUDENTS VALUES(
    18,'AMAY','RAJ','AMAY@gmail.com',22
)

SELECT * FROM CSE_STUDENTS


-- DDL--> DATA DEFINITION LANGUAGE -- STRUCTURE MAINTAIN DEFINE (  DDL CMDS --> CREATE ALTER DROP SHOW DESCRIBE ) -- AUTO COMMIT -- 

-- DML --> DATA MANIPULATION LANGUAGE -- DATA MANIPULATION (  DML CMDS --> INSERT UPDATE DELETE SELECT ) -- AUTO COMMIT NHI HOTI WE CAN REVERET IT


-- DCL --> DATA CONTROL LANGUAGE -- DATA KE UPER SECURITY (  DCL CMDS --> GRANT REVOKE ) -- NO ONE CAN ACCESS

-- DQL --> DATA QUERY LANGUAGE -- GET DATA -- NO COMMIT

-- TCL --> TRANSACTION CONTROL LANGUAGE  -- DELETE AND THEN REVERSE(CALLBACK)  -- COMMIT AND ROLLBACK

-- RDBMS --> MULTIPLE DEVICES
-- DBMS  --> SINGLE DEVICE



