-- DDL --> DATA DEFINATION LANGUAGE


--  SQL ENGINE --> SQL QUERY MEIN ERRORS FIND OUT KRTA HAI 
-- CREATE DATABASE COLLEGES;-- DDL FIRST COMMAND


-- DATA TYPES
-- 1. INT
-- 2.CHAR -- > 255 MEMORY LETE HAI ---> FIXED SIZE AND MORE MEMORY USE -- USE IT IN PHONE_NO EXAMPLE
-- EG . NAME CHAR(30) --> NAME = GOVIND TOH REST MEMORY WASTE HOGI 
-- 3. VARCHAR -- > MEMORY EFFICIENT JITNI USKI VALUE DENGE ()
-- LIMITATION OF VARCHAR WITH LIMIT 
-- FIX OR USSSE KM HI VALUE LE SKTA HAI USSE JYDA NHI HOGI

-- 4. FLOAT
CREATE DATABASE IF NOT EXISTS COLLEGES;-- ERROR NI AAYEGI BUT WARNING AA SKTI HAI 

SHOW DATABASES;

DROP DATABASE COLLEGES;

USE COLLEGES;

-- DROP TABLE STUDENT;

-- DROP DATABASE COLLEGES;


--  CONSTRINTS --> SPECIAL FEATURES ABOUT THE COLUMN-- OPTIONALS HOTE HAI
-- 1. NOT NULL
-- 2. NULL
-- 3. PRIMARY KEY--> WOH DUPLICATE NI HOGI AUR NULL NI HOGI
-- 4. UNIQUE
-- 5. AUTO INCREMENT --> EK VALUE BDA DEGA 



CREATE TABLE STUDENT (
    RTUNO INT ,
    NAME CHAR (30) NOT NULL,
    AGE FLOAT

    
);

SHOW TABLES;

DESCRIBE STUDENT;
DESC STUDENT;

--  ALTER COMMAND -- FOR CHANGING THE TABLE
-- RENAME COMMADS FOR RENAMING THE TABLE

ALTER TABLE student RENAME COLUMN NAME TO STUDENTNAME ;

DESCRIBE STUDENT;
INSERT INTO STUDNET VALUES(1,'GOVIND',22);

INSERT INTO STUDNET VALUES(2,'NAGORI',22);

--  QUESTION 
-- EMP ID NAME SELLARY 
CREATE DATABASE IF NOT EXISTS COMPANY;

USE COMPANY;

CREATE TABLE EMPLOYEE(
    EMP_ID INT ,
    NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    SALARY INT
);

DESCRIBE EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(1,'GOVIND','GOVIND@gmail',2220000);
INSERT INTO EMPLOYEE VALUES(2,'NAGORI','NAGORI@gmail',220000); 

INSERT INTO EMPLOYEE VALUES(3,'DILIP','DILIP@gmail',22300); 
INSERT INTO EMPLOYEE VALUES(4,'ARYAN','ARYAN@gmail',22200); 

INSERT INTO EMPLOYEE VALUES(5,'DEVANSH','DEVANSH@gmail',233200); 

INSERT INTO EMPLOYEE VALUES(6,'AYUSH','AYUSH@gmail',123300);

INSERT INTO EMPLOYEE VALUES(7,'AMAN','AMAN@gmail',2220000);

INSERT INTO EMPLOYEE VALUES(8,'ANKIT','ANKIT@gmail',22200);

INSERT INTO EMPLOYEE VALUES(9,'AKSHAT','AKSHAT@gmail',22200);

INSERT INTO EMPLOYEE VALUES(10,'AMAY','AMAY@gmail',22200);



SELECT * FROM EMPLOYEE;

SELECT NAME FROM employee;

-- TRUNCATE CMDS IS USED FOR ERRASE ALL THE DATA OF TABLE OR DELETE ALL THE DATA
-- TRUNCATE EMPLOYEE;
TRUNCATE TABLE employee;


-- TRUNCATE AND DELETE CMD MEIN DIFFER KYO HAI ?

-- 
-- CREATE -- DB AND TABLE
-- DROP -- DB AND TABLE
-- RENAME -- DB AND TABLE
-- IF NOT EXISTS -- DB AND TABLE
-- SHOW -- DB AND TABLE
-- USE 
-- DESCRIBE -- TABLE
-- DESC -- TABLE
-- ALTER -- TABLE
-- TRUNCATE -- TABLE
-- ALTER TABLE ADD -- COLUMN


-- QUESTION
-- 1 . CREATE TABLE 
-- 2 . ALTER SE TABLE ADD COLUMN NAME ID MAIL
-- 3 . USING ALTER CITY
-- 4 . RENAME THE CITY TO ADDRESS
-- 5 . RENAME DATA TYPE OF TABLE USING ALTER COMMAND
-- 6 . DROP THE TABLE AND DATABASE
-- 7 . TRUNCATE THE TABLE
