-- Active: 1770164352852@@127.0.0.1@3306@colleges
-- date 11-02-2026



--  SELECT QUERY ---> 
-- 1. DB MEIN JO RECORD HAI UNKE BARE MEIN HM SELEKT KRTA HAI


USE COLLEGES;

CREATE TABLE STUDENTS (
    ID INT,
    NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    SALARY INT, 
    CGPA INT
);

-- CHANGING CGPA INT TO FLOAT
ALTER TABLE STUDENTS
MODIFY CGPA FLOAT;

DROP TABLE STUDENTS;
INSERT INTO STUDENTS VALUES (1,'GOVIND JANGID','GOVIND@123',10000 , 9.7);

INSERT INTO students VALUES (2,'NAGORI','NAGORI@123',10000 , 9.5);

INSERT INTO students VALUES (3,'DILIP','DILIP@123',10000 , 9.9);

INSERT INTO students VALUES (4,'ARYAN','ARYAN@123',10000 , 9.8);

INSERT INTO students VALUES (5,'DEVANSH','DEVANSH@123',10000 , 9.6);



SELECT * FROM STUDENTS;
SELECT NAME FROM STUDENTS;
SELECT NAME,EMAIL FROM STUDENTS;



SELECT NAME AS STDNAME , EMAIL FROM STUDENTS;
-- AS is a keyword  jo name ko stdname mein change kr dega 

SELECT NAME FROM STUDENT WHERE NAME = 'NAGORI';
-- WHERE MEIN CONDITION LAGA SAKTE HAI

DELETE FROM STUDENTS WHERE NAME = 'GOVIND JANGID';
-- DELETE MEIN WHERE MEIN CONDITION LAGA SAKTE HAI


--  OPERATORS
-- 1. ARITHMETIC OPERATORS
-- 2. RELATIONAL OPERATORS
-- 3. LOGICAL OPERATORS

-- 1 )ARITHMETIC OPERATORS
-- 1. +
-- 2. -
-- 3. *
-- 4. /

-- 2 )RELATIONAL OPERATORS
-- 1. = 
-- 2. <>
-- 3. >
-- 4. <
-- 5. >=
-- 6. <=
-- 7. != NOT EQUALS TO

-- 3 )LOGICAL OPERATORS
-- 1. AND
-- 2. OR
-- 3. NOT


UPDATE STUDENTS SET CGPA = CGPA +.1;
-- SAFE MODE KI WARNINGS AATI HAI AGR HM COMPLETE COLUMN MEIN CHANGE KRTE HAI TOH


SELECT * FROM studentS;

SELECT * FROM STUDENTS WHERE CGPA<9.5;

SELECT * FROM STUDENTS WHERE CGPA>9.5;

SELECT * FROM STUDENTS WHERE CGPA!=9.7;

SELECT * FROM STUDENTS WHERE CGPA<>9.7;
-- USE --> 


-- LOGICAL OPERATORS
SELECT * FROM STUDENTS WHERE CGPA > 9.5 AND CGPA < 9.9;
-- USE --> WHEN BOTH CONDITIONS ARE TRUE AND VALUE OF CGPA IS BETWEEN 9.5 AND 9.9

SELECT * FROM STUDENTS WHERE CGPA > 9.5 OR CGPA < 9.9;

SELECT * FROM STUDENTS WHERE NOT CGPA > 9.5 OR CGPA <2.9;
-- SBSE PHLE NOT EXCUTE HOGA THEN OR 

SELECT * FROM STUDENTS WHERE NOT(CGPA < 9.5 OR CGPA <2.9);
-- IS WALE CASE MEIN PHLE OR EXECUTE HOGA THEN NOT EXCUTE HOGA

-- PRIORITY ORDER OF LOGICAL OPERATORS
-- 1. BRACKETS
-- 2. NOT
-- 3. AND
-- 4. OR

-- BETWEEN OPERATOR
SELECT * FROM STUDENTS WHERE CGPA BETWEEN 9.5 AND 10;
-- CGPA BETWEEN 9.5 AND 9.9

-- IN OPERATOR
SELECT * FROM STUDENTS WHERE CGPA IN(9.5,9.9,10);
-- CGPA IN (9.5,9.9,10)

SELECT * FROM STUDENTS;

-- LIKE OPERTORS 
-- % IS A WILDCARD CHARACTER
-- _ IS A WILDCARD CHARACTER -- USE FOR SPACING 
SELECT * FROM STUDENTS WHERE NAME LIKE 'g%';-- start with g

SELECT * FROM STUDENTS WHERE NAME LIKE '%ga%';-- khi bhi ga ho continues

SELECT * FROM STUDENTS WHERE NAME LIKE '%g';-- end with g

SELECT * FROM STUDENTS WHERE NAME LIKE '_A';

-- NAME WHICH START WITH G

SELECT NAME FROM STUDENTS WHERE NAME LIKE '_A%';

SELECT NAME FROM STUDENTS WHERE NAME LIKE '%R_';

SELECT * FROM STUDENTS WHERE NAME LIKE 'G%' AND CGPA >= 9;

SELECT name FROM studentS WHERE NAME LIKE "[g]%";