-- date 13 feb 2026
-- LECT NO 6
USE COLLEGES;

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS VALUES (6,'GOVIND JALA','GOVIND@123',10000 , NULL);


-- topic---> agreegate functions

-- 1.AVG FUNCTION

SELECT AVG(CGPA) FROM STUDENTS;
-- if any null values are there then avg will not count them and not return in avg or we can say ignore krega 

-- 2.MAX FUNCTION

SELECT MAX(CGPA) as "MAX CGPA in students " FROM STUDENTS;

-- 3.MIN FUNCTION

SELECT MIN(`CGPA`) FROM STUDENTS;

-- 4.COUNT FUNCTION

SELECT COUNT(`CGPA`) FROM STUDENTS;-- HOW MANY RECORDS (CGPA) ARE THERE IN STUDENTS TABLE
-- if any null values are there then count will not count them

SELECT COUNT(*) as "number of students" FROM STUDENTS;

-- 5.SUM FUNCTION

SELECT SUM(cgpa) FROM STUDENTS;


-- SUB QUERY---> NESTED QUERY 
-- SUB QUERY FIRST THEN SUPER QUERY RUN
-- FIRST INNER QUERY THEN OUTER QUERY

-- SYNTAX

SELECT  * from students where CGPA = (SELECT MAX(CGPA) FROM STUDENTS);


CREATE TABLE IT_STD (
    ID INT,
    NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    SALARY INT, 
    CGPA FLOAT
);

INSERT INTO IT_STD VALUES (1,'GOVIND JANGID','GOVIND@123',10000 , 7);
INSERT INTO IT_STD VALUES (2,'GORUAV NAGORI','NAGORI@123',10000 , 9.7);
INSERT INTO IT_STD VALUES (3,'DILIP KUMAWAT','DILIP@123',10000 , 8.7);
INSERT INTO IT_STD VALUES (4,'AMAN KUMAR','AMAN@123',10000 , 7.7);

CREATE TABLE ITSTD (
    ID INT,
    NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    SALARY INT, 
    CGPA FLOAT
)

SELECT * from IT_STD ;

-- INSERT DATA FROM IT_STD TO ITSTD TABLE

INSERT INTO ITSTD SELECT * FROM IT_STD WHERE CGPA < 8.5;

SELECT * FROM ITSTD;

ALTER TABLE ITSTD
ADD COLUMN BRANCH VARCHAR(30);

-- even -- it 
-- odd -- cse

UPDATE ITSTD SET BRANCH = 'IT' WHERE ID%2 = 0;
UPDATE ITSTD SET BRANCH = 'CSE' WHERE ID%2 = 1;

SELECT * FROM ITSTD;

SELECT AVG(CGPA) FROM itstd WHERE `BRANCH`='IT';